application: the-rapa-game
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:

- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /styles
  static_dir: styles
  secure: always

- url: /scripts
  static_dir: scripts
  secure: always